# Generated by Django 3.2 on 2021-06-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='form',
            name='lname',
        ),
    ]
