# Generated by Django 3.2 on 2021-06-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210601_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='date',
        ),
    ]
