# Generated by Django 3.2 on 2021-07-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
