# Generated by Django 3.2 on 2021-07-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='discharge',
        ),
        migrations.RemoveField(
            model_name='form',
            name='familyten',
        ),
        migrations.RemoveField(
            model_name='form',
            name='work',
        ),
        migrations.RemoveField(
            model_name='form',
            name='worktype',
        ),
        migrations.AddField(
            model_name='form',
            name='anesthesia',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='diagnosis',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='digitalex',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='estimate',
            field=models.CharField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AddField(
            model_name='form',
            name='gender',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='otherhis',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='pathological',
            field=models.CharField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='address',
            field=models.CharField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='age',
            field=models.CharField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='anus',
            field=models.TextField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='bleeding',
            field=models.TextField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='burning',
            field=models.TextField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='constipation',
            field=models.TextField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='itching',
            field=models.TextField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='othercom',
            field=models.TextField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='pain',
            field=models.TextField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.CharField(default='DEFAULT VALUE', max_length=12),
        ),
        migrations.AlterField(
            model_name='form',
            name='prolepse',
            field=models.TextField(default='DEFAULT VALUE', max_length=122),
        ),
    ]
