# Generated by Django 3.2 on 2021-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210708_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
