# Generated by Django 3.2 on 2021-07-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_form_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
    ]
